### ISSUE TITLE
Add drupal migrate module link to Trello

### ISSUE THREAD

**Issue by kimpham54** [islandora-interest-groups/Islandora-Metadata-Interest-Group#50]
Not sure how to join the board in Trello to post the link, but here's the Drupal module the DSU at UTSC is working on to migrate metadata into CLAW: https://github.com/digitalutsc/dragomans_migrate

This is a complete work in progress. More info is in the wiki! @rtilla1

**Comment by rtilla1** [comment]
Thank you. I'll add this. For future reference, here's a link to the Trello board https://trello.com/b/J6ciWrqa/sample-mods-rdf-mapping-tool
